reference-architecture:
    gpudb_nvidia_playbook:
        description: playbook for installing nvidia for gpudb
        cuda_deb: "/tmp/cuda-repo-ubuntu1604-8-0-local_8.0.35-1_ppc64el.deb"
        driver_level: "nvidia-361"
        dkms_deb: "/tmp/dkms_2.2.0.3-2ubuntu14_all.deb"

switches:
    mgmt:
    -   hostname: mgmtswitch1
        ipv4-addr: 192.168.0.5
        rack-id: rack1
        userid: admin
        password: admin
    data:
    -   hostname: dataswitch1
        ipv4-addr: 9.3.89.24
        rack-id: rack1
        userid: admin
        password: admin
nodes:
    controllers:
    -   hostname: controller-1
        userid-ipmi: ADMIN
        password-ipmi: ADMIN
        port-ipmi: 5
        port-pxe: 6
        port-eth10: 35
        port-eth11: 59/2
        mac-ipmi: 0c:c4:7a:4d:86:aa
        ipv4-ipmi: 192.168.0.101
        mac-pxe: 0c:c4:7a:53:4d:00
        ipv4-pxe: 9.3.3.69
        rack-id: rack1
        template: controllers
        chassis-part-number: CSE-938BH-R1620BP
        chassis-serial-number: C9380AE15AH0247
        model: SYS-5038ML-H8TRF
        serial-number: S13656825718481
        openstack-mgmt-addr: 172.29.236.1
        openstack-stg-addr: 172.29.244.1
        openstack-tenant-vlan-addr: 0.0.0.0
        openstack-tenant-vxlan-addr: 172.29.240.1
        external1-addr: 10.40.204.2
        external2-addr: ''
        mac-eth10: 68:05:ca:39:85:90
        mac-eth11: 68:05:ca:39:85:91
    compute:
    -   hostname: compute-1
        userid-ipmi: ADMIN
        password-ipmi: admin
        port-ipmi: 10
        port-pxe: 12
        port-eth10: 10
        port-eth11: 27
        mac-ipmi: a0:42:3f:30:62:b5
        ipv4-ipmi: 172.17.0.4
        rack-id: rack1
        template: compute
        architecture: ppc64
        mac-pxe: a0:42:3f:31:1c:62
        ipv4-pxe: 9.3.3.58
        openstack-mgmt-addr: 172.29.236.4
        openstack-stg-addr: 172.29.244.4
        openstack-tenant-vlan-addr: 0.0.0.0
        openstack-tenant-vxlan-addr: 172.29.240.4
        external1-addr: 10.40.204.5
        external2-addr: ''
        mac-eth10: 98:be:94:00:fa:c5
        mac-eth11: 98:be:94:00:fa:c6
ipaddr-mgmt-network: 192.168.0.0/24
ipaddr-mgmt-switch:
    rack1: 192.168.0.5
ipaddr-data-switch:
    rack1: 9.3.89.24
redundant-network: false
userid-default: ubuntu
password-default: passw0rd
userid-mgmt-switch: admin
password-mgmt-switch: admin
userid-data-switch: admin
password-data-switch: admin
internal-floating-ipaddr: 9.3.89.55
external-floating-ipaddr: 9.3.89.56
networks:
    external1:
        description: Organization site or external network
        addr: 10.40.204.0/24
        broadcast: 10.40.204.255
        gateway: 10.40.204.1
        dns-nameservers: 9.3.1.200
        dns-search: aus.stglabs.ibm.com
        method: static
        eth-port: eth10
    external2:
        description: Interface for eth11
        method: manual
        eth-port: eth11
    openstack-mgmt:
        description: OpenStack Management Network
        bridge: br-mgmt
        method: static
        tcp_segmentation_offload: false
        addr: 172.29.236.0/22
        vlan: 210
        eth-port: eth10
    openstack-stg:
        description: OpenStack Management Network
        bridge: br-storage
        method: static
        tcp_segmentation_offload: false
        addr: 172.29.244.0/22
        vlan: 220
        eth-port: eth10
    openstack-tenant-vxlan:
        description: OpenStack Tenant vxlan Network
        bridge: br-vxlan
        method: static
        addr: 172.29.240.0/22
        vlan: 230
        eth-port: eth11
    openstack-tenant-vlan:
        description: OpenStack Tenant vlan Network
        bridge: br-vlan
        method: static
        addr: 0.0.0.0/1
        eth-port: eth11
    ceph-replication:
        description: Ceph Replication vlan Network
        addr: 172.29.248.0/22
        bridge: br-replication
        method: static
        vlan: 240
        eth-port: eth11


node-templates:
    controllers:
        hostname: controller
        userid-ipmi: ADMIN
        password-ipmi: ADMIN
        cobbler-profile: ubuntu-14.04.4-server-amd64.sm
        os-disk: /dev/sda
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        bond-interfaces:
        -   - eth10
            - eth11
        ports:
            pxe:
                rack1:
                - 6
                - 3
                - 1
            ipmi:
                rack1:
                - 5
                - 4
                - 2
            eth10:
                rack1:
                - 35
                - 28
                - 31
            eth11:
                rack1:
                - 59/2
                - 59/3
                - 59/4
        networks:
        - openstack-mgmt
        - openstack-stg
        - openstack-tenant-vlan
        - openstack-tenant-vxlan
        - external1
        - external2
    compute:
        hostname: compute
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-14.04.4-server-ppc64el
        os-disk: /dev/sdl
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        bond-interfaces:
        -   - eth10
            - eth11
        ports:
            pxe:
                rack1:
                - 12
            ipmi:
                rack1:
                - 10
            eth10:
                rack1:
                - 10
            eth11:
                rack1:
                - 27
        networks:
        - openstack-mgmt
        - openstack-stg
        - openstack-tenant-vlan
        - openstack-tenant-vxlan
        - external1
        - external2

    ceph-osd:
        hostname: cephosd
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-14.04.4-server-ppc64el
        os-disk: /dev/sdl
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        bond-interfaces:
        -   - eth10
            - eth11
        ports:
            pxe:
                rack1:
                - 11
                - 13
                - 15
            ipmi:
                rack1:
                - 9
                - 14
                - 16
            eth10:
                rack1:
                - 11
                - 44
                - 41
            eth11:
                rack1:
                - 30
                - 45
                - 42
        networks:
        - external1
        - openstack-stg
        - ceph-replication
        journal-devices:
        - /dev/sda
        - /dev/sdb
        osd-devices:
        - /dev/sdd
        - /dev/sde
        - /dev/sdf
        - /dev/sdg
        - /dev/sdh
        - /dev/sdi
